#!/usr/bin/env bash
# installing nginx on the web-01

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'nginx HTTP'
sh -c 'echo "Hello World!" > /var/www/html/index.html' 
service nginx restart
