#!/usr/bin/env bash
# Displays "Best School" 10 times using a while loop

# Initialize counter
counter=0

# Loop until counter reaches 10
while [ $counter -lt 10 ]
do
	echo "Best School"
	((counter++))
done
